# Generated by Django 4.0 on 2021-12-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
    ]
